/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraph;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author nadae
 */
public class OptiInstanceDessin extends javax.swing.JPanel {
    
    /**
     * Pour dessiner on utilise un jPanel
     * Certaines Infos retrouvées sur internet
     * obj.drawRect(0,0,100,100); //dessiner un rectangle 
     *      -> drawRect(x-position, y-position, width, height)
     * obj.setColor(Color.blue); //definir une couleur
     * obj.fillRect(200,0,100,100); remplir le rectangle
     *      -> fill new rectangle with color blue
     *      -> (x-position, y-position, width, height)
     */
    
        //attribut et constantes
    
    /**
     * Creates new form OptiInstanceDessin
     */
    public OptiInstanceDessin() {
        initComponents();
        
    }
    public void dessiner(){
        repaint();
    }
    
    /**
     * 
     */
    
    public void paint(Graphics g){
        super.paint(g);
        paintBox(g,100,100,100,100);
        paintProduit(g,200,200,100,100);
    }
    /**
     * Dessiner les box
     * 
     */
    
    public void paintBox(Graphics g, int xB,int yB, int widthB, int heightB){
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(Color.pink); //definir une couleur
        g2.fillRect(xB,yB,widthB,heightB);
    }
    
    
    /**
     * Dessiner les produits
     * 
     */
    public void paintProduit(Graphics g, int xP,int yP, int widthP, int heightP){
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(Color.white); //definir une couleur
        g2.fillRect(200,200,100,100);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
