/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraph;

import java.awt.Dimension;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import modele.Box;
import modele.Produit;

/**
 *
 * @author nadae
 */
public class OptiAfficherDessinInstance extends javax.swing.JFrame {

    private Set<Box> box;
    private Set<Produit> produit;
    
    /**
     * Creates new form OptiDessin
     */
    public OptiAfficherDessinInstance() {
        initComponents();
        
        this.box = new HashSet<>();
        this.produit = new HashSet<>();
        
    }
    
    /**
     * contructeur par donnees
     */
    
    public OptiAfficherDessinInstance(Set<Box> b , Set<Produit> p){
        this();
        this.box = b;
        this.produit =p;
        afficherDessinInstance();
    }
        /**
     * Methode qui permet d'afficher les box et les produits de l'instance selectionnée
     */
    private void afficherDessinInstance(){
        
        
        //!!!!!!!!!!!!!!!!!!//
        //!!le probleme ici est que je n'arrive pas a afficher les deux jscroll au meme temps
        //et je n'affiche pas un jscroll avec une bar de scroll
        
        
        
        // creation d'une frame + taille
        JFrame frame = new JFrame("Dessin Instance");
        frame.setPreferredSize(new Dimension(1000, 800));
        //dessin des box
        OptiBoxDessin dB = new OptiBoxDessin(box);
        JScrollPane scroll = new JScrollPane(dB);
        scroll.setHorizontalScrollBar(new JScrollBar());
        scroll.setPreferredSize(new Dimension(900, 200));
        scroll.setAutoscrolls(true);
        scroll.setLocation(1, 1);
        scroll.setAlignmentX(TOP_ALIGNMENT);
        
        
        //dessin des produits
        OptiProduitDessin dP = new OptiProduitDessin(produit);
        JScrollPane scroll2 = new JScrollPane(dP);
        scroll2.setHorizontalScrollBar(new JScrollBar());
        scroll2.setPreferredSize(new Dimension(900, 200));
        scroll2.setAutoscrolls(true);
        scroll.setLocation(1, 500);
        scroll.setAlignmentX(BOTTOM_ALIGNMENT);
        //JLabel label = new JLabel("hello");
        //frame.add(label);
        
        //scroll.add(dB);
        frame.add(scroll);
        frame.add(scroll2);
        frame.pack();
        frame.setVisible(true);
    }
    @Override
    public String toString() {
        return "box:"+this.box+"produit"+this.produit; //To change body of generated methods, choose Tools | Templates.
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptiAfficherDessinInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptiAfficherDessinInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptiAfficherDessinInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptiAfficherDessinInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptiAfficherDessinInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
