/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraph;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Set;
import modele.Box;

/**
 *
 * @author nadae
 */
public class OptiBoxDessin extends javax.swing.JPanel {
    
    /**
     * Pour dessiner on utilise un jPanel
     * Certaines Infos retrouvées sur internet
     * obj.drawRect(0,0,100,100); //dessiner un rectangle 
     *      -> drawRect(x-position, y-position, width, height)
     * obj.setColor(Color.blue); //definir une couleur
     * obj.fillRect(200,0,100,100); remplir le rectangle
     *      -> fill new rectangle with color blue
     *      -> (x-position, y-position, width, height)
     */
    
        //attribut et constantes
    //set des box
    private Set<Box> setAffichageBox;
    //constante qui permet de separer les box entre eux
    private static int hauteurSeparateurBox =0;
    private static final int separateurBox=10;
    /**
     * Creates new form OptiInstanceDessin
     * @param b
     */
    public OptiBoxDessin(Set<Box> b) {
        initComponents();
        this.setAffichageBox =b;
        
    }
    public void dessiner(){
        repaint();
    }
    
    /**
     * 
     */
    @Override
    public void paint(Graphics g){
        super.paint(g);
        paintBox(g,setAffichageBox);
    }
    /**
     * Dessiner les box
     * 
     * @param g
     * @param yB
     * @param b
     */
    
    public void paintBox(Graphics g, Set<Box> b){
        Graphics2D g2 = (Graphics2D) g;
        
        for (Box objBox : b) {
            g2.setColor(Color.pink); //definir une couleur
            
            //System.out.println(objBox.getHauteur());
            //System.out.println(hauteurSeparateurBox);
            //System.out.println(hauteurSeparateurBox + separateurBox);
            //System.out.println("\n");
            g2.fillRect(0 , hauteurSeparateurBox , (objBox.getLongueur())/5 , (objBox.getHauteur())/5);
            
            g2.drawRect(0, hauteurSeparateurBox +(objBox.getHauteur())/5, (objBox.getLongueur())/5, separateurBox);
            hauteurSeparateurBox += objBox.getHauteur()/5+separateurBox;
        }
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
