/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraph;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Set;
import modele.Box;
import modele.Produit;

/**
 *
 * @author nadae
 */
public class OptiProduitDessin extends javax.swing.JPanel {

    //attributs
    //set des produits
    private Set<Produit> setAffichageProduit;
    //constante qui permet de separer les produits entre eux
    private static int hauteurSeparateurProduit =0;
    private static final int separateurProduit=5;
    /**
     * Creates new form OptiProduitDessin
     */
    public OptiProduitDessin(Set<Produit> p) {
        initComponents();
        this.setAffichageProduit =p;
    }

    public void dessiner(){
        repaint();
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        paintProduit(g,setAffichageProduit);
    }
    
    /**
     * Dessiner les box
     * 
     */
    public void paintProduit(Graphics g,Set<Produit> p){
        Graphics2D g2 = (Graphics2D) g;
        for (Produit objProd : p) {
            g2.setColor(Color.white); //definir une couleur
            g2.fillRect(0 , hauteurSeparateurProduit , (objProd.getLongueur())/5 , (objProd.getHauteur())/5);
            
            g2.drawRect(0, hauteurSeparateurProduit +(objProd.getHauteur())/5, (objProd.getLongueur())/5, separateurProduit);
            hauteurSeparateurProduit += objProd.getHauteur()/5+separateurProduit;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
