/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraph;

import java.awt.Color;
import java.awt.Font;
import java.util.*;
import javax.swing.*;
import modele.*;

/**
 *
 * @author nadae
 */
public class OptiInterface extends javax.swing.JFrame {

        //attributs
    //dans cette interface, nous allons afficher
    //liste d'instance selectionnes
    List<Instance> listInstanceInterface;
    //liste de solution
    List<Solution> listSolutionInterface;
    
    
    /**
     * Creates new form OptiInterface
     */
    public OptiInterface() {
        initComponents();
        initFenetre();
    }

    /**
     * Methode initFenetre
     * Initialisation de a taille, de la couleur et des elements composants cette fenetre
     */
    
    private void initFenetre(){
        this.setTitle("OptiBox");
        this.setSize(1430, 700); 
        
        //couleurs
        //les boutons
        this.jButtonInstance.setBackground(Color.decode("#90CAF9"));
        this.jButtonInstance.setForeground(Color.WHITE);
        this.jButtonSolution.setBackground(Color.decode("#90CAF9"));
        this.jButtonSolution.setForeground(Color.WHITE);
        //le titre
        this.jTitre.setForeground(Color.decode("#546E7A"));
        this.jTitre.setFont(new Font("Tratto", Font.BOLD, 30));
        this.setVisible(true);
    }
    
    /**
     * Methode addListInstanceVu
     * elle permet d'afficher la liste des instances
     */
    private void addListInstanceVu(){
        DefaultListModel listInstanceVu = new DefaultListModel();
        for (Instance object : listInstanceInterface)
            listInstanceVu.addElement(object);
        this.jListInstance.setModel(listInstanceVu);
    }
    
    /**
     * Methode addListSolutionVu
     * elle permet d'afficher la liste des instances
     */
    private void addListSolutionVu(){
        DefaultListModel listSolutionVu = new DefaultListModel();
        for (Solution object : listSolutionInterface)
            listSolutionVu.addElement(object);
        this.jListSolution.setModel(listSolutionVu);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButtonInstance = new javax.swing.JButton();
        jButtonSolution = new javax.swing.JButton();
        jTitre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInstance = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSolution = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonInstance.setText("Telecharger Instance");
        jButtonInstance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstanceActionPerformed(evt);
            }
        });

        jButtonSolution.setText("Solution");
        jButtonSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolutionActionPerformed(evt);
            }
        });

        jTitre.setText("OptiBox");

        jListInstance.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListInstance);

        jListSolution.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListSolution);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInstance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(jTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSolution))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonInstance)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSolution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInstanceActionPerformed

    private void jButtonSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSolutionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptiInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptiInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptiInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptiInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptiInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInstance;
    private javax.swing.JButton jButtonSolution;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JList<String> jListInstance;
    private javax.swing.JList<String> jListSolution;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jTitre;
    // End of variables declaration//GEN-END:variables
}
